language: php

php:
  - 7.0

before_script:
- cp .env.travis .env
- mysql -e 'create database homestead;'
- travis_retry composer self-update
- composer install --prefer-source --no-interaction --dev
- php artisan containers:add User Welcome Authentication Authorization Application Debugger Payment Paypal Stripe Settings SocialAuth Contact Email Country
- php artisan migrate
- php artisan db:seed

script: vendor/bin/phpunit
